### ISSUE TITLE
New task creation box problem.

### ISSUE THREAD

**Issue by zli213** [zli213/SynergyStudy#41]
1. Default comes with two tags, as shown in the figure below, which need to be removed.
![CleanShot 2024-01-15 at 20 32 27@2x](https://github.com/zli213/SynergyStudy/assets/127060502/c5af276d-b4e3-4337-896b-5e2496089c03)
2. When creating a new tag, adding a space does not automatically break the tag boundary, and the orange highlight will continue indefinitely. Encountered the following error when trying:
![CleanShot 2024-01-15 at 20 35 05@2x](https://github.com/zli213/SynergyStudy/assets/127060502/ce1f92f2-b3f7-40bc-aaaf-9715ec025c84)
![CleanShot 2024-01-15 at 20 35 21@2x](https://github.com/zli213/SynergyStudy/assets/127060502/4a2d4671-c40c-4068-a0e5-d88596e5d9f8)
3. The text box still highlights the text in bold even when the tag keywords are not triggered.
![image](https://github.com/zli213/SynergyStudy/assets/127060502/a513da4b-9988-4510-a233-0f6924453a8b)
4. Clicking the add button does not produce any response.

**Comment by jlmjkfd** [comment]
Fixed
